### ISSUE TITLE
Connl04 format

### ISSUE THREAD

**Issue by robinsonOdhiambo** [malcolmgreaves/rex#2]
How does connl04 format look like, for labeling sentences

**Comment by malcolmgreaves** [comment]
Iirc, it's the same as this format (1). Essentially, each line is a token. Columns are he token text, leammatized form, need tag, pos tag. An empty newline separates sentences.


(1) http://www.cnts.ua.ac.be/conll2003/ner/

**Comment by malcolmgreaves** [comment]
I've made some updates to this code. Right now, it supports learning from data that's annotated with relations in a slightly different format. An example of this format is in the test code [1]. There's also a larger file that's suitable for evaluation. It's in the repository [2] as the '.*corp' files.

[1] https://github.com/malcolmgreaves/rex/blob/master/src/test/scala/org/rex/io/UiucRelationFmtTest.scala#L98
[2] https://github.com/malcolmgreaves/rex/tree/master/data/uiuc_cog_comp_group-entity_and_relation_recognition_corpora
